import type { Metadata } from "next";
import { Inter, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

const ibmPlexMono = IBM_Plex_Mono({
  variable: "--font-ibm-plex-mono",
  subsets: ["latin"],
  weight: ["400", "500"],
});

export const metadata: Metadata = {
  title: "DecentraVM — Build Autonomous Agents That Execute",
  description:
    "DVM is the runtime environment for AI agents — a high-performance, scalable, and secure infrastructure designed to execute code generated by AI.",
  icons: {
    icon: "/LOGOD.png",
  },
  openGraph: {
    title: "DecentraVM — Build Autonomous Agents That Execute",
    description:
      "DVM is the runtime environment for AI agents — a high-performance, scalable, and secure infrastructure designed to execute code generated by AI.",
    images: [{ url: "/embed.png" }],
    siteName: "DecentraVM",
  },
  twitter: {
    card: "summary_large_image",
    title: "DecentraVM — Build Autonomous Agents That Execute",
    description:
      "DVM is the runtime environment for AI agents — a high-performance, scalable, and secure infrastructure designed to execute code generated by AI.",
    images: ["/embed.png"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${inter.variable} ${ibmPlexMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
