import Link from "next/link";

export default function Hero() {
  return (
    <section id="hero" className="relative min-h-screen flex items-center justify-center text-center pt-16 overflow-hidden">
      {/* Grid background */}
      <div className="absolute inset-0 hero-grid-bg" />

      <div className="relative z-10 max-w-[800px] px-6">
        <h1 className="text-[clamp(2.2rem,5.5vw,4rem)] font-extrabold leading-[1.15] mb-5 tracking-tight">
          Build Autonomous
          <br />
          Agents That Execute
        </h1>
        <p className="text-[clamp(1rem,2vw,1.2rem)] text-[#666] max-w-[700px] mx-auto mb-8">
          DVM is the runtime environment for AI agents — a high-performance, scalable, and secure infrastructure designed to{" "}
          <strong className="text-black">execute code generated by AI.</strong>
        </p>
        <div className="flex gap-4 justify-center flex-wrap">
          <Link
            href="https://api.avm.codes/"
            target="_blank"
            className="px-7 py-3 rounded-none text-sm font-semibold bg-black text-white border border-black hover:bg-white hover:text-black hover:-translate-y-0.5 transition-all"
          >
            Get started
          </Link>
          <Link
            href="https://docs.decentravm.top/"
            target="_blank"
            className="px-7 py-3 rounded-none text-sm font-semibold border border-black text-black bg-white hover:bg-black hover:text-white hover:-translate-y-0.5 transition-all"
          >
            See docs
          </Link>
        </div>
        <div className="flex gap-6 justify-center mt-6">
          <Link href="https://www.linkedin.com/in/decentra-vm-18b3473ab/" target="_blank" className="text-sm text-black/40 hover:text-black transition-colors">LinkedIn</Link>
          <Link href="https://github.com/Decentra-VM" target="_blank" className="text-sm text-black/40 hover:text-black transition-colors">GitHub</Link>
          <Link href="https://x.com/Decentra_VM" target="_blank" className="text-sm text-black/40 hover:text-black transition-colors">X</Link>
        </div>
      </div>
    </section>
  );
}
